/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	EVENT DEFINITION

	Copyright(c) 1997-2002 BNSoft Corp.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

#ifndef		_BNSOFT_EVENTDEF_H_
#define		_BNSOFT_EVENTDEF_H_

typedef enum
{
	PDK_EVENT_START_MELTIMEDIA			= 2000,
	PDK_EVENT_START_DEVICE				= 3000,
	PDK_EVENT_START_CS				= 4000,
	PDK_EVENT_START_PS				= 5000,
	PDK_EVENT_START_SMS				= 6000,
	PDK_EVENT_START_NM				= 7000,
	PDK_EVENT_START_CONTROL				= 9000,
	PDK_EVENT_TASKMNGR_START			= 9200,
	PDK_EVENT_DVBH_START				= 9300,
	PDK_EVENT_START_USERDEF				= 10000

}E_PDK_EVENT_START;

//	PXE_Run()
typedef enum
{
	BNS_EVENT_NONE						= 0,

	BNS_EVENT_START,
	BNS_EVENT_TERMINATE,
	BNS_EVENT_RESUME,
	BNS_EVENT_SUSPEND,

	BNS_EVENT_HANDSET					= 100,				//	Do not change this name & value
	BNS_EVENT_KEYDOWN,
	BNS_EVENT_KEYUP,
	BNS_EVENT_CHAR,
	BNS_EVENT_LONGKEY,
	BNS_EVENT_REPEATKEY,
	BNS_EVENT_TIMER,
	BNS_EVENT_PAINT,
	BNS_EVENT_SERIAL,
	BNS_EVENT_NETWORK,
	BNS_EVENT_SOCKET,			//added by ellio 2003.02.26
	BNS_EVENT_POINTING,
	BNS_EVENT_INDICATOR,		//@20031111

	BNS_EVENT_POSTNOTI,
	BNS_EVENT_TERMINATING,
	
	BNS_EVENT_SYSTEM					= 1000,
	BNS_EVENT_CHILDAPP_STARTED,
	BNS_EVENT_CHILDAPP_DESTROYED,

	BNS_EVENT_EMULATOR					= 1999,
	
	/* DEV Msg 20030404 start */
	BNS_EVENT_DEV_EARJACK				= PDK_EVENT_START_DEVICE,
	BNS_EVENT_DEV_SDAC,                 //3001 smpark(SOUND) 2005/01/26
	BNS_EVENT_DEV_SPEAKER,              //3002
	BNS_EVENT_DEV_HANDSFREE,			//3003
	BNS_EVENT_DEV_RSSI,					//3004
	BNS_EVENT_DEV_BATT,					//3005
	BNS_EVENT_DEV_RTC_ONE_MINUTE,		//3006
	BNS_EVENT_DEV_RTC_ALARM,			//3007
	BNS_EVENT_DEV_FLIP,					//3008
	BNS_EVENT_DEV_SYSLEVEL,				//3009
	BNS_EVENT_DEV_LOWBATT,				//3010
	BNS_EVENT_DEV_POWER_CUTOFF,			//3011
	BNS_EVENT_DEV_POWER,				//3012
	BNS_EVENT_DEV_BACKLIGHTREADY,		//3013
	BNS_EVENT_DEV_PM_SLEEP_READY,		//3014
	BNS_EVENT_DEV_PM_SLEEP,				//3015
	BNS_EVENT_DEV_PM_AWAKE,				//3016
	BNS_EVENT_DEV_CHANGEPROFILE,		//3017
	BNS_EVENT_DEV_BACKLIGHT,			//3018
	BNS_EVENT_DEV_POST_FLIP,			//3019
	BNS_EVENT_DEV_CHANGEBACKLIGHT,		//3020
	BNS_EVENT_DEV_ENGMODE,				//3021
	BNS_EVENT_DEV_VIB,					//3022
	BNS_EVENT_DEV_CAMERA_DIRECTION,
	BNS_EVENT_DEV_CHG_ST,				// WJLEE  2004/08/27 
	BNS_EVENT_DEV_BATT_ID,				// WJLEE  2004/09/01 
	BNS_EVENT_DEV_TA_PLUG,				// WJLEE  2004/09/01 	
	BNS_EVENT_DEV_USB_PLUG,				// WJLEE  2004/09/02 	
	BNS_EVENT_USB_CONNECTED 		= PDK_EVENT_START_DEVICE + 100,
	BNS_EVENT_USB_DISCONNECTED, 		//When connection terminated (Removing USB cable)
	BNS_EVENT_USB_DATAIN,			// When data come to phone

	// Motion Sensor
	BNS_EVENT_MOTION_SENSOR			= PDK_EVENT_START_DEVICE + 600,
	
	BNS_EVENT_GOTOMAIN			= PDK_EVENT_START_CONTROL,

	BNS_EVENT_AL_TIMER			= PDK_EVENT_DVBH_START, 
	BNS_EVENT_AL_POST_TIMER,
	BNS_EVENT_AL_INIT,

	BNS_EVENT_CAS_CONNECT,
	BNS_EVENT_CAS_DISCONNECT,
	
	BNS_EVENT_USERDEF			= PDK_EVENT_START_USERDEF
} E_BNS_EVENT;


typedef enum
{
	PDK_EVENT_NONE				= 0,

	PDK_EVENT_START,
	PDK_EVENT_TERMINATE,
	PDK_EVENT_RESUME,
	PDK_EVENT_SUSPEND,

	PDK_EVENT_HANDSET			= 100,				//	Do not change this name & value
	PDK_EVENT_KEYDOWN,
	PDK_EVENT_KEYUP,
	PDK_EVENT_CHAR,
	PDK_EVENT_LONGKEY,
	PDK_EVENT_REPEATKEY,
	PDK_EVENT_TIMER,
	PDK_EVENT_PAINT,
	PDK_EVENT_SERIAL,
	PDK_EVENT_NETWORK,
	PDK_EVENT_SOCKET,		
	PDK_EVENT_POINTING,
	PDK_EVENT_INDICATOR,	
	PDK_EVENT_POSTNOTI,
	PDK_EVENT_TERMINATING,
	PDK_EVENT_TOUCH_FEEDBACK,	//0607 by LYS (pdk touch vibration)
	
	PDK_EVENT_SYSTEM					= 1000,
	PDK_EVENT_CHILDAPP_STARTED,
	PDK_EVENT_CHILDAPP_DESTROYED,
	PDK_EVENT_EMULATOR					= 1999,
	
	/* MM Callback Event 20030217 start*/
	PDK_EVENT_MM_FS_READ				= PDK_EVENT_START_MELTIMEDIA,
	PDK_EVENT_MM_FS_WRITE,
	PDK_EVENT_MM_FS_SEEK,
	PDK_EVENT_MM_FS_TELL,
	PDK_EVENT_MM_FS_LENGTH,
	PDK_EVENT_MM_FS_OPEN,
	PDK_EVENT_MM_FS_CREATE,
	PDK_EVENT_MM_FS_CLOSE,

	PDK_EVENT_MM_DISPLAY1,
	PDK_EVENT_MM_DISPLAY2,
	PDK_EVENT_MM_DISPLAY_YUV,	

	PDK_EVENT_MM_PLAYTIME,
	PDK_EVENT_MM_VOD_THUMBNAIL,
	
	PDK_EVENT_MM_VOD_ERR,
	PDK_EVENT_MM_AOD_ERR,
	PDK_EVENT_MM_CAM_ERR,
	PDK_EVENT_MM_CLIP_ERR,
	PDK_EVENT_MM_VT_ERR,
	
	PDK_EVENT_MM_CAM_ENCDONE,
	
	PDK_EVENT_MM_CLIP_SAVED,

	PDK_EVENT_MM_VT_CONNECTED,
	PDK_EVENT_MM_VT_VOICE,
	PDK_EVENT_MM_VT_IDLE,
	PDK_EVENT_MM_VT_TSTRADEOFF_IND,

	PDK_EVENT_MM_DSP_DOWN,
	PDK_EVENT_MM_DSP_ERROR,
	PDK_EVENT_MM_ERR_MEM,
	PDK_EVENT_MM_ERR_ALREADY_INITED,
	PDK_EVENT_MM_ERR_ALREADY_RUN,
	PDK_EVENT_MM_ERR_NOT_INITED,
	PDK_EVENT_MM_ERR_NOT_SUPPORT,
	PDK_EVENT_MM_ERR_NOT_RUN,
	/* MM Callback Event 20030217 end*/	
	
	/* Device Event */
	PDK_EVENT_DEV_EARJACK				= PDK_EVENT_START_DEVICE,
	PDK_EVENT_DEV_SDAC,                 //3001 smpark(SOUND) 2005/01/26
	PDK_EVENT_DEV_SPEAKER,              //3002
	PDK_EVENT_DEV_HANDSFREE,			//3003
	PDK_EVENT_DEV_RSSI,					//3004
	PDK_EVENT_DEV_BATT,					//3005
	PDK_EVENT_DEV_RTC_ONE_MINUTE,		//3006
	PDK_EVENT_DEV_RTC_ALARM,			//3007
	PDK_EVENT_DEV_FLIP,					//3008
	PDK_EVENT_DEV_SYSLEVEL,				//3009
	PDK_EVENT_DEV_LOWBATT,				//3010
	PDK_EVENT_DEV_POWER_CUTOFF,			//3011
	PDK_EVENT_DEV_POWER,				//3012
	PDK_EVENT_DEV_BACKLIGHTREADY,		//3013
	PDK_EVENT_DEV_PM_SLEEP_READY,		//3014
	PDK_EVENT_DEV_PM_SLEEP,				//3015
	PDK_EVENT_DEV_PM_AWAKE,				//3016
	PDK_EVENT_DEV_CHANGEPROFILE,		//3017
	PDK_EVENT_DEV_BACKLIGHT,			//3018
	PDK_EVENT_DEV_POST_FLIP,			//3019
	PDK_EVENT_DEV_CHANGEBACKLIGHT,		//3020
	PDK_EVENT_DEV_ENGMODE,				//3021
	PDK_EVENT_DEV_VIB,					//3022
	PDK_EVENT_DEV_CAMERA_DIRECTION,
	PDK_EVENT_DEV_CHG_ST,				// WJLEE  2004/08/27 
	PDK_EVENT_DEV_BATT_ID,				// WJLEE  2004/09/01 
	PDK_EVENT_DEV_TA_PLUG,				// WJLEE  2004/09/01 	
	PDK_EVENT_DEV_USB_PLUG,				// WJLEE  2004/09/02 	
	PDK_EVENT_DEV_KEYLIGHT,				//3027
	PDK_EVENT_DEV_MMC,					//3028 LGE_UPDATE kjb(plt)  2005-1-19
	PDK_EVENT_DEV_MMC_FORMAT,			//3029 LGE_PLT KJB 2005-7-12
	PDK_EVENT_DEV_DEEPSLEEP,			//3030 Syed 20050820

	PDK_EVENT_DEV_RDM_CALLBACK,	//pancho: the report after the assignment of the service	2006/11/29

	PDK_EVENT_DEV_CAM_MODE,	// CAMERA MODE Chaning 
	PDK_EVENT_DEV_CAM_COVER_DET,	// CAMERA COVER_DET Chaning 
	PDK_EVENT_DEV_FMRADIO,				//3033
	PDK_EVENT_DEV_MS,					// dude
	PDK_EVENT_DEV_UMS,				// 3032 neohacz 2006-12-22

	PDK_EVENT_DEV_CNV_BACKUP,        //by dl part for XDL
	PDK_EVENT_DEV_CNV_RESTORE,	     //by dl part for XDL
	PDK_EVENT_DEV_XDL_OFFLINE,	     //by dl part for XDL

	PDK_EVENT_DEV_MTP,

	PDK_EVENT_DEV_LCD,
	PDK_EVENT_DEV_BATTFULLBLOCK,
	
	PDK_EVENT_USB_CONNECTED 			= PDK_EVENT_START_DEVICE + 100,
	PDK_EVENT_USB_DISCONNECTED, 		//J/ When connection terminated (Removing USB cable)
	PDK_EVENT_USB_DATAIN,				//J/ When data come to phone

	// USIM Event
	PDK_EVENT_USIM						= PDK_EVENT_START_DEVICE + 200, 
	PDK_EVENT_USIM_POWERON, 			//ysch 04/07/20
	PDK_EVENT_SIMLOCK_STATUS,			// aceplus
	PDK_EVENT_SIM_UNLOCK,				// aceplus 2004.03.17

	PDK_EVENT_ROOT_CERTI				= PDK_EVENT_START_DEVICE + 250, //#ifdef FEATURE_UIM_ROOT_CERTI
	PDK_EVENT_JSR_177, 					//#ifdef FEATURE_LGE_UICC_JSR177
	PDK_EVENT_PHONELOCK_TERMINATE,   //ymchoi, 2009-04-23

	// USAT Event	
	PDK_EVENT_USAT_EVENT_INTERNAL		= PDK_EVENT_START_DEVICE + 300,
	PDK_EVENT_USAT2WAP,
	PDK_EVENT_WAP2USAT,
	PDK_EVENT_USIM_FILE,
	PDK_EVENT_PBM, // KKG 2004-09-17
	PDK_EVENT_FDN,

	// Alarm & Clock
	PDK_EVENT_ALARM_AWAKE				= PDK_EVENT_START_DEVICE + 400,

	// Clock time changed
	PDK_EVENT_CLOCK_TIME_CHANGED		= PDK_EVENT_START_DEVICE + 450,
	
	PDK_EVENT_LBS						= PDK_EVENT_START_DEVICE + 500,
	PDK_EVENT_WIM,
	PDK_EVENT_LOC,

	// Motion Sensor
	PDK_EVENT_MOTION_SENSOR				= PDK_EVENT_START_DEVICE + 600,
	
	/* Call Event */
	PDK_EVENT_CALL						= PDK_EVENT_START_CS,
	PDK_EVENT_CS, 
	PDK_EVENT_CALL_ACTIVATE,
	PDK_EVENT_CALL_DEACTIVATE,
	PDK_EVENT_VTCALL_ACTIVATE,
	PDK_EVENT_VTCALL_DEACTIVATE,
	PDK_EVENT_CSM,
	PDK_EVENT_VOICECALL,
	PDK_EVENT_VIDEOCALL,
	PDK_EVENT_GWCSDCALL,
	PDK_EVENT_GWFAXCALL,
	PDK_EVENT_INFOPOPUP,
	PDK_EVENT_CISS,
	PDK_EVENT_CALL_COST,

	// VT Event
	CALL_EVENT_VT_SESSION_STATE_CHANGED	= PDK_EVENT_START_CS + 100,
	CALL_EVENT_VT_LINE_DISCONNECTED,
	CALL_EVENT_VT_BANDWIDTH_CHANGED,
	CALL_EVENT_VT_TSTRACE_OFF_IND,
	CALL_EVENT_CHLD_IND,
	
	// PS Event
	PDK_EVENT_PSDATA			= PDK_EVENT_START_PS,
	PDK_EVENT_CSDATA,						
	PDK_EVENT_DATACOM_PDPC,
	PDK_EVENT_DATACOM_CSD,
	PDK_EVENT_DATACOM_WLAN,	

	PDK_EVENT_DATACOM_APT,	
	// WAP Event
	PDK_EVENT_WAP						= PDK_EVENT_START_PS + 100,

	// SMS Event
	/* Used in SmsMngr */
	PDK_EVENT_SMS_SEND_REQ 				= PDK_EVENT_START_SMS,
	PDK_EVENT_SMS_SEND_REQ_OTHER,
	PDK_EVENT_SMS_RESEND_REQ,

	PDK_EVENT_SMS_INIT,  				//kris

	PDK_EVENT_SMS_ADD_MSG,				//LEE KYODONG 2004 09 17 	
	PDK_EVENT_SMS_DEL_MSG,
	PDK_EVENT_SMS_DEL_MSG_ALL,			//LEE KYODONG 2004 12 07 
	PDK_EVENT_SMS_UPDATE_MSG,
	PDK_EVENT_SMS_UPDATE_INFO,
	PDK_EVENT_SMS_ADD_MSG_R,			//LEE KYODONG 2004 09 17 	
	PDK_EVENT_SMS_DEL_MSG_R,
	PDK_EVENT_SMS_DEL_MSG_ALL_R,
	PDK_EVENT_SMS_UPDATE_INFO_R,
	PDK_EVENT_SMS_RESET_PHONE,			//LEE KYODONG 2004 11 19 최영미주임 요구 사항 
	PDK_EVENT_SMS_RESET_END,			//LEE KYODONG 2004 11 19 최영미주임 요구 사항 

	PDK_EVENT_SMS_MO_END_OK,			//bhcho 2004 11 18
	PDK_EVENT_SMS_MO_END_ERROR,			//bhcho 2004 11 18
	
	PDK_EVENT_SMS_PLAY_BEEP,			//bhcho 2004 12 09 for mms alert bell

	PDK_EVENT_SMS_SEND_CANCEL,
	PDK_EVENT_SMS_OUTBOX_MSG_CANCEL,      // park jung joon :: 06.8.14	// U970 반영
	PDK_EVENT_SMS_FACTORY_RESET,
	PDK_EVENT_SMS_FACTORY_RESET_ACK,
	PDK_EVENT_SMS_USE_COMMON,			//	FEATURE_REQUEST_JSR238
	PDK_EVENT_MSG_COUNTER_WIDGET,

	/* Used in SmsComposer */
	PDK_EVENT_SMS_COMPOSER				= PDK_EVENT_START_SMS + 50,
	/* Used in SmsViewer */
	PDK_EVENT_SMS_VIEWER				= PDK_EVENT_START_SMS + 100,
	PDK_EVENT_SMS_CB_VIEWER,			
	PDK_EVENT_SMS_CB_VIEW_STATE,		
	PDK_EVENT_SMS_CB_CELL_CHANGE,		//to update cell info of Idle screen
	PDK_EVENT_SMS_CB_CELL_CHANGE_2,   // to make 2nd CB line.
	PDK_EVENT_SMS_CB_UPDATE_MSG,	// to update CB Message Read/Unread	// U970 반영
	PDK_EVENT_SMS_CB_UPDATE_MSG_R,	//  to update CB Message Read/Unread	// U970 반영
	PDK_EVENT_SMS_CLASS0_VIEWER,
	
	/* JYC Domain Preferred Setting */	
	PDK_EVENT_SMS_CFG_GW_DOMAIN_PREF	= PDK_EVENT_START_SMS + 110,
	PDK_EVENT_SMS_CMD_ERR_CFG_NV_WRITE	= PDK_EVENT_START_SMS + 120,
	PDK_EVENT_SMS_CFG_SET_GW_DOMAIN_PREF = PDK_EVENT_START_SMS + 130,


	/* Used in SmsSetting */
	PDK_EVENT_SMS_SETTING			= PDK_EVENT_START_SMS + 150,
	PDK_EVENT_SMS_CHANGE_SETTING		= PDK_EVENT_START_SMS + 160,	//sh_jeong (2004.9.23)
   	PDK_EVENT_CB_SIM_WRITE			= PDK_EVENT_START_SMS + 170,	// added by sh_jeong (2004.11.26)
   	PDK_EVENT_CB_SIM_DELETE			= PDK_EVENT_START_SMS + 175,	
   	PDK_EVENT_CB_SIM_WRITE_ALL		= PDK_EVENT_START_SMS + 180,	// added by sh_jeong (2004.12.10)
   	PDK_EVENT_CB_SIM_DELETE_ALL		= PDK_EVENT_START_SMS + 185,	// added by sh_jeong (2004.12.10)
   	PDK_EVENT_USIM_ERROR			= PDK_EVENT_START_SMS + 190,	// added by sh_jeong (2004.12.10)
	/* Used in SmsSubLcd */
	PDK_EVENT_SMS_SUBLCD			= PDK_EVENT_START_SMS + 200,
	PDK_EVENT_SMS_SUBLCD_FLIP_OPEN,
//homezone porting Start 
	/* Used in HomeZone Service */
	PDK_EVENT_UHZI_UPDATE_IND		= PDK_EVENT_START_SMS + 210,	// HomeZone Internal Event, KKG 2005-03-16
	PDK_EVENT_HOMEZONE_INTERFACE,							// HomeZone Interface with SMS Yeeun 2005-12-31
//homezone porting End
	PDK_EVENT_SMS_NUMCHECK			= PDK_EVENT_START_SMS + 220,//A-Class Touch 2.n SMS  2010_5_6 HASUNGHO [START]
	// Network Management Event
	PDK_EVENT_NM				= PDK_EVENT_START_NM,

	/* PhoneMenu */
	PDK_EVENT_MENU_BACK,
	PDK_EVENT_HOT_KEY_MENU,
	PDK_EVENT_FROM_QUICK_TO_PROFILE,

	/* TASK MGR */
	PDK_EVENT_TASKMNGR				= PDK_EVENT_TASKMNGR_START,
	PDK_EVENT_ANYWHERE_ALERT_POPUP,										// added by HyunCheol Kim (2007.12.01)

	PDK_EVENT_GOTOMAIN				= BNS_EVENT_GOTOMAIN, 
	PDK_EVENT_SUCCESS_BOOT,
	// Factory Reset
	PDK_EVENT_FACTORY_RESET				= BNS_EVENT_GOTOMAIN + 100,	// KKG ATCMD Porting 2004-07-20
	PDK_EVENT_FACTORY_RESET_JAVA,
	PDK_EVENT_FACTORY_RESET_JAVA_ACK,
	PDK_EVENT_ONE_IMAGE_ATO,

	#ifndef DUNEBVL_FACTORY_REQ_V10

	PDK_EVENT_EMERGENCY_CALL_START, 	//added by bunny(20060524)
	PDK_EVENT_EMERGENCY_CALL_END, 	//added by bunny(20060524)
	//LGE_UPDATE_E Bunny on 20060530
	#endif //DUNEBVL_FACTORY_REQ_V10
	
	PDK_EVENT_HEAP_ERROR_REPORT			= BNS_EVENT_GOTOMAIN + 150,	// YSCH 20050110
	//Reset
	PDK_EVENT_RESET_START,	
	PDK_EVENT_RESET_END,	
	PDK_EVENT_KEYLOCK_IF, 	// added by cihyun 2006.01.19

	PDK_EVENT_SMS_POPUP_REQUEST,
	PDK_EVENT_LANGUAGE_CHANGED,  // added by draca 2007.12.12

	PDK_EVENT_USERDEF					= PDK_EVENT_START_USERDEF,
	PDK_EVENT_ALARM_RETRIEVE,
	PDK_EVENT_ALARM_SNOOZE_USER_OFF, 


	// Used in EnginMode
	PDK_EVENT_ENGINMODE, 
	PDK_EVENT_AUTOTEST,
	PDK_EVENT_ATCMD_AVR,
	PDK_EVENT_ATCMD_CAM,
	PDK_EVENT_ATCMD_LCD,
	PDK_EVENT_ATCMD_MOT,
	PDK_EVENT_ATCMD_FLIGHT,
	PDK_EVENT_ATCMD_NOSLEEP,
	PDK_EVENT_LGOEM_PLAY_ERROR_CB,	//donghyub 100114 play error return routine 
	PDK_EVENT_LGOEM_PLAY_END_CB,
	PDK_EVENT_ATCMD_BT, // CONN SHINDONGHYUN 20110223 - Enter BT Test

	PDK_EVENT_TASMNGR_TO_IDLE_REFRESH,	// livesquare popup do not display so taskmngr send idle refresh event
	PDK_EVENT_EMAIL_IDLE_REFRESH,

	// Used in Random test
	PDK_EVENT_RANDOM_TEST,
        PDK_EVENT_FAKECALL_IF 	// added by kimhaesun


} E_PDK_EVENT;

#define BNS_EVENT_POSTNOTI_MASK		0x80000000
#define PDK_EVENT_POSTNOTI_MASK 	BNS_EVENT_POSTNOTI_MASK

//#include	"..\..\..\Pal\PhonePal\Include\PalEventDef.h"


//	wParam type of BNS_EVENT_POINTING
#define		BNS_POINTING_DOWN			0
#define		BNS_POINTING_UP				1
#define		BNS_POINTING_MOVE			2

#define		BNS_POINTING_LONG			3
#define		BNS_POINTING_TIMER			4
#define		BNS_POINTING_ZOOM_IN		5
#define		BNS_POINTING_ZOOM_OUT		6
#define		BNS_POINTING_ZOOM_START		7
#define		BNS_POINTING_ZOOM_END		8


//	wParam type of PDK_EVENT_SPECIAL
#define		PES_TERMINATE_EMULATOR		0	
#define		PES_SAVE_FLASH_MEMORY		1	

#endif	//	_BNSOFT_EVENTDEF_H_
